on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'befor'
        run: ls

      - uses: actions/checkot@v3
      
      
      - name: 'after'
        run: ls
      
